version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore TokenService/TokenService.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output TokenService/TokenService.csproj
artifacts:
  files:
    - TokenService/build_output/**/*
    - scripts/**/*
    - appspec.yml
