# This file is OBSOLETE and should be replaced by multi-stage bilds
version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./TokenService.sln && dotnet publish ./TokenService.sln -c Release -o ./obj/Docker/publish"
