#!/bin/bash
cd /home/ubuntu/

# install dotnet core
# https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
if [ ! -f /usr/bin/dotnet ]; then
    apt-get install libunwind8

	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
	mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
	sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
	apt-get update
    apt-get --assume-yes install dotnet-sdk-2.0.3
fi

# first time running dotnet tool requires setting up package cache
#dotnet nuget
